import time
from pathlib import Path
from typing import ClassVar

import numpy as np
import numpy.typing as npt
import pandas as pd
from data_handler import sklearn_train_test_split
from sklearn.compose import ColumnTransformer, make_column_transformer
from sklearn.metrics import r2_score
from sklearn.model_selection import (GridSearchCV, GroupKFold, KFold,
                                     LearningCurveDisplay, LeaveOneGroupOut,
                                     RandomizedSearchCV, ShuffleSplit,
                                     StratifiedKFold, TimeSeriesSplit,
                                     ValidationCurveDisplay, cross_validate)
from sklearn.pipeline import Pipeline, make_pipeline
from types_config import (AcceptEstimatorType, AcceptPreprocessorType,
                          CvParameters, CvResults, CvStrategy, CvType,
                          ScoringFunctionType, SearchCvHyperparamType,
                          SearchCvParameters, SearchCvType, SearchOuterCv, Tcv,
                          Tmodel, Tpreprocessor)
from visualisation import plot_time_series_detection

# Expected parameter for a given search class use to tune hyperparameters
SEARCH_EXPECTED_PARAM = {
    GridSearchCV.__name__: ["cv"],
    RandomizedSearchCV.__name__: ["cv", "n_iter"]
}


class Model[Testimator, Tmodel]():
    _estimator_class: type[Testimator] # scikit-learn estimator
    _default_params: ClassVar[dict[str, int | float | str]] = {} # default model parameters

    model: Tmodel # either a classifier or a regressor or a pipeline

    def __init__(self, model_instance: Tmodel):
        """Base class to build machine learning model."""
        self.model = model_instance


    @classmethod
    def _create_estimator(cls, model_params: dict[str, int | float | str]) -> Testimator:
        """
        To instanciate an estimator with the given parameter or default.

        Parameters
        ----------
        model_params: model parameters
        """
        # Get class attribute
        estimator_cls: type[Testimator] = getattr(cls, "_estimator_class")
        default_params: dict[str, int | float | str] = getattr(cls, "_default_params")

        # Set parametes
        params = default_params | model_params

        # Instanciate the estimator
        print(f"\n*******************\nBuild a {estimator_cls.__name__} model"
              f"{f' with parameter(s) {str(params)}' if model_params else ''}")
        return estimator_cls(**params)

    @classmethod
    def build(cls: type[Model[Testimator, Testimator]],
              **model_params) -> Model[Testimator, Testimator]:
        """
        Initialise a machine learning model.

        In this case, model is necessarily an estimator and not a pipeline. This is why we use the
        syntax Model[Testimator, Testimator].

        Parameters
        ----------
        **model_params: model parameters
        """
        return cls(model_instance=cls._create_estimator(model_params))

    @classmethod
    def build_pipeline(cls: type[Model[Testimator, Pipeline]],
                       transformers: list[Tpreprocessor],
                       **model_params) -> Model[Testimator, Pipeline]:
        """
        Set up a column transformers.

        For example to deal with numerical and categorical values:
        - Encoding of categorical variables
        - Scaling of numerical variables

        In this case, model is necessarily a pipeline. This is why we use the syntax
        Model[Testimator, Pipeline].

        Parameters
        ----------
        transformers: a list that is either made of transformers which are applied on the whole
        data or tuples of the form (transformer, columns) with transformer the given transformation
        to apply and columns the data to transform.

        Columns is either got with the make_column_selector class of scikit-learn or by using the
        columns property of a pandas DataFrame (in this cas it's required to convert the
        pandas.Index into a list of string)

        **model_params: model parameters
        """
        # Column transformer past ? There are past as tuples of the form (transformer, columns).
        column_transformer_steps, left_over_steps = [], []
        for ele in transformers:
            if isinstance(ele, tuple):
                column_transformer_steps.append(ele)
            else:
                left_over_steps.append(ele)

        # Initialise a column transformer to allow different columns of the input to be transformed
        # separately and the features generated by each transformer will be concatenated to form a
        # single feature space
        if column_transformer_steps:
            preprocessor = make_column_transformer(*column_transformer_steps)
            left_over_steps.insert(0, preprocessor)

        # Instanciate the model
        left_over_steps.append(cls._create_estimator(model_params))

        # Instanciate the pipeline
        print(f"Set up a pipeline to build a machine learning model.")
        return cls(model_instance=make_pipeline(*left_over_steps))


    ############
    # PROPERTY #
    ############
    @property
    def is_regressor(self) -> bool:
        return False

    @property
    def is_pipeline(self) -> bool:
        """Some models can either be used with or without a pipeline."""
        return isinstance(self.model, Pipeline)


    ###########
    # STARTER #
    ###########
    def start(self,
              x_train: pd.DataFrame = pd.DataFrame(),
              x_test: pd.DataFrame = pd.DataFrame(),
              y_train: pd.Series = pd.Series(),
              y_test: pd.Series = pd.Series()):
        """
        Either perform a machine learning model or start a pipeline to sequentially apply a list
        of transformers to pre-process the data.

        Parameters
        ----------
        x_train: training data

        x_test: testing data

        y_train: training target

        y_test: testing target
        """
        if x_train.empty and y_train.empty:
            raise Exception("A training data set and target are required.")

        if isinstance(self.model, Pipeline):
            # Start the pipeline
            print("Start a simple pipeline with the given steps: "
                  f"{self.model.named_steps}.")
            start = time.time()

            # Train the model
            self.train(x_train, y_train)

            # Pipeline over
            n_iter = f"{getattr(self.model[-1], 'n_iter_')[0]} iterations " \
                if "n_iter_" in self.model[-1].__dict__ else " "
            print(f"Pipeline over: {n_iter}in {time.time() - start:.3f}s")
        else:
            # Simply train the model
            self.train(x_train, y_train)

        if not x_test.empty and not y_test.empty:
            # Predict target + chek model performance
            self.predict(x_train, x_test, y_train, y_test)


    ###################
    # TRAIN & PREDICT #
    ###################
    def train(self,
              x_train: pd.DataFrame,
              y_train: pd.Series,
              **kwargs) -> None:
        """
        Train the model using training data.

        Parameters
        ----------
        x_train: training data

        y_train: training targets

        **kwargs: additional parameters such as sample_weight: by default samples are equally
        weighted, else give more importance to samples with higher weight.
        """
        getattr(self.model, "fit")(x_train, y_train, **kwargs)


    #############
    # PARAMETER #
    #############
    def get_hyperparameters(self) -> dict[str, any]:
        """Get model hyperparameters."""
        return getattr(self.model, "get_params")()

    def set_hyperparameters(self, **parameters) -> None:
        """Set model hyperparameters."""
        getattr(self.model, "set_params")(**parameters)

    def set_output(self, transform: str = "pandas") -> None:
        """To configure  all steps of the pipeline to output DataFrame."""
        getattr(self.model, "set_output")(transform=transform)

    @property
    def pipeline(self) -> Pipeline:
        """Return the model explicitly typed as Pipeline."""
        if not isinstance(self.model, Pipeline):
            raise TypeError("Model should be a Pipeline to be able to call this method.")
        return self.model

    def get_output_features(self):
        """
        Get output feature names for transformation. In order to call this method, training the
        model is required.
        """
        if not isinstance(self.pipeline[0], ColumnTransformer):
            raise TypeError("In order to get output feature names for transformation, a pipeline "
                            "with transformers must be done.")
        return self.pipeline[0].get_feature_names_out()


    #####################
    # MODEL PERFORMANCE #
    #####################
    def print_training_accuracy(self,
                                y_train: pd.Series,
                                y_predicted: npt.NDArray[np.generic]) -> None:
        """Print model performance with training data."""
        print(f"The train accuracy is {self.get_training_accuracy(y_train, y_predicted):.3f}.")

    def get_training_accuracy(self,
                              y_train: pd.Series,
                              y_predicted: npt.NDArray[np.generic]) -> float:
        """Get model performance with training data."""
        return (y_train == y_predicted).mean()

    def print_testing_accuracy(self, x_test: pd.DataFrame, y_test: pd.Series) -> None:
        """Print model performance with testing data."""
        print("The test accuracy is "
              f"{self.get_testing_accuracy(x_test, y_test):.3f}")

    def get_testing_accuracy(self, x_test: pd.DataFrame, y_test: pd.Series) -> float:
        """Get model performance with testing data."""
        return getattr(self.model, "score")(x_test, y_test)

    def print_r2_score(self, y_data: pd.Series, y_predicted: npt.NDArray[np.generic]) -> None:
        """print r2 (coefficient of determination) regression score function."""
        return print(f"the r2 score is {r2_score(y_data, y_predicted):.3f}")

    def get_r2_score(self, y_data: pd.Series, y_predicted: npt.NDArray[np.generic]) -> float:
        """get r2 (coefficient of determination) regression score function."""
        return r2_score(y_data, y_predicted)


    ####################
    # CROSS VALIDATION #
    ####################
    def _assert_cv_parameters(self,
                             expected_parameters: list[str],
                             params: CvParameters | SearchCvParameters,
                             cv_name: str) -> None:
        """
        For cross-validation (check generalization performance) and search cross-validation (tune
        hyperparameters) some parameters depending of the cv strategy are required.
        """
        assert None not in [
            getattr(params, field) for field in params._fields if field in expected_parameters
        ], f"Parameters {', '.join(expected_parameters)} are required to perform a {cv_name}."

    def _revert_negation(self,
                        results: CvResults,
                        scoring: ScoringFunctionType | None) -> CvResults:
        """Revert the negation apply to the error metric to get the actual error."""
        if scoring and isinstance(scoring, str) and scoring.startswith("neg_"):
            results["test_score"] = -results["test_score"]
            if "train_score" in (res := results):
                results["train_score"] = -res["train_score"]
        return results

    def print_cross_validate(self, scores: CvResults, verbose: bool = False) -> None:
        """Print cross validation result."""
        # Testing error
        mean_score, std_score = \
            self.get_cross_validate_mean_and_std(scores['test_score'])
        print("\nThe mean cross-validated testing error is: "
             f"{mean_score:.3f} ± {std_score:.3f}"
             f" with an average fitting time of {scores['fit_time'].mean():.3f}")

        if verbose:
            print(f"\nTest scores accross the various step of the cv: {scores['test_score']}\n")

        # Training error
        if "train_score" in (res := scores):
            mean_score, std_score = \
                self.get_cross_validate_mean_and_std(res['train_score'])
            print("The mean cross-validated training error is "
                  f"{mean_score:.3f} ± {std_score:.3f}")

            if verbose:
                print(f"\nTrain scores accross the various step of the cv: "
                      f"{res['train_score']}\n")

    def get_cv_estimator(self, scores: CvResults) -> list[AcceptEstimatorType
                                                          | AcceptPreprocessorType]:
        """
        The estimator objects for each cv split. This is available only if return_estimator
        parameter of make_cross_validate is set to True.
        """
        if "estimator" in (res := scores):
            return res["estimator"]
        raise Exception("In order to get the estimator objects for each cv split, return_estimator"
                        " must be set to True.")

    def get_mean_cv_results(self,
                            scores: CvResults,
                            columns: list[int | float]) -> pd.DataFrame:
        """
        When performing multiple cross-validation for hyperparameter tuning using method such as as
        grid-search, it's possible to store the cross-validation values corresponding to each set
        of hyperparameters.
        """
        # Get cross-validation values for each set of hyperparameters
        cv_results = [
            getattr(ele[-1], "cv_results_").mean(axis=0) for ele in self.get_cv_estimator(scores)
        ]

        return pd.DataFrame(cv_results, columns=columns).aggregate(["mean", "std"]).T

    def get_cross_validate_mean_and_std(self,
                                        scores: npt.NDArray[np.float64]) \
                                        -> tuple[float, float]:
        """Get the mean/std of a cross_validation strategy."""
        return scores.mean(), scores.std()

    def make_cross_validate(self,
                            x_data: pd.DataFrame,
                            y_data: pd.Series,
                            cv_strategy: CvStrategy = "KFold",
                            cv_params: CvParameters = CvParameters(n_splits=5),
                            scoring: ScoringFunctionType | None = None,
                            return_train_score: bool = False,
                            return_estimator: bool = False,
                            groups: npt.NDArray[np.int64] | None = None,
                            **kwargs) -> CvResults:
        """
        Generic methods to either perform a kfold or shuffle split cross-validation in order to
        evaluate the generalization performance of the model.

        Parameters
        ----------
        x_data: the input data use to fit the model

        y_data: the target variable to try to predict

        cv_strategy: which cross-validation strategy to use

        cv_params: additional parameter of the the cross-validation strategy, use the default
        5-fold strategy

        scoring: strategy to evaluate the perfomance of the estimator across cv splits Scikit-learn
        allow the use of any metric, like 'mean_absolute_error' into a score to be used in cross
        validate. In order to do so, pass a string of the error metric with and additional neg_
        such as 'neg_mean_absolute_error'.

        return_train_score: whether to include train scores

        return estimator: whether to return the estimators fitted on each split

        groups: group labels for the samples used while splitting the dataset into train/test set.
        Only used in conjunction with a "Group" cv instance, e.g. GroupKFold
        """
        cv: CvType
        msg: str
        match cv_strategy:
            case "GroupKFold":
                # K-fold iterator variant with non-overlapping groups. Each group will appear
                # exactly once in the test set across all folds.
                cv = self.group_kfold_cv_generator()
                msg = "Group k-fold cross-validation"
            case "KFold":
                # Provides train/test indices to split data in train/test sets. Split dataset into
                # k consecutive folds (without shuffling by default).
                cv = self.kfold_cv_generator(cv_params.n_splits,
                                             shuffle=cv_params.shuffle,
                                             random_state=cv_params.random_state)
                msg = f"K-fold cross-validation with K={cv_params.n_splits}"
            case "LeaveOneGroupOut":
                # Provides train/test indices to split data such that each training set is
                # comprised of all samples except ones belonging to one specific group
                cv = self.leave_one_group_out_cv_generator()
                msg = "Leave one group out k-fold cross-validation"
            case "ShuffleSplit":
                # Yields indices to randomly split data into training and test sets.
                self._assert_cv_parameters(["test_size"], cv_params, cv_strategy)
                cv = self.shuffle_split_cv_generator(cv_params.n_splits,
                                                     test_size=cv_params.test_size)
                msg = f"Shuffle split cross-validation with n={cv_params.n_splits} and " \
                    f"test_size={cv_params.test_size}"
            case "StratifiedKFold":
                # Variation of KFold that returns stratified folds. The folds are made by
                # preserving the percentage of samples for each class in target.
                cv = self.stratified_kfold_cv_generator(cv_params.n_splits,
                                                        shuffle=cv_params.shuffle,
                                                        random_state=cv_params.random_state)
                msg = f"Stratified k-fold cross-validation with K={cv_params.n_splits}"
            case "TimeSeriesSplit":
                # Provides train/test indices to split time-ordered data.
                cv = self.time_series_split_cv_generator(n_splits=cv_params.n_splits)
                msg = "Cross-validation for time series"

        print(f"\n{msg}{f' using the metric {scoring}.' if scoring is not None else '.'}")

        results: CvResults = cross_validate(
            self.model if "model" not in kwargs.keys() else kwargs["model"],
            x_data,
            y_data,
            cv=cv,
            scoring=scoring,
            return_train_score=return_train_score,
            error_score="raise",
            n_jobs=2,
            return_estimator=return_estimator,
            groups=groups)

        return self._revert_negation(results, scoring)


    #############################
    # CROSS-VALIDATION STRATEGY #
    #############################
    def group_kfold_cv_generator(self) -> GroupKFold:
        """Set up a group k-fold cross-validation strategy."""
        return GroupKFold()

    def kfold_cv_generator(self,
                           n_splits: int,
                           shuffle: bool= False,
                           random_state: int | None = None) -> KFold:
        """
        Set up a k-fold cross-validation strategy.

        Parameters
        ----------
        n_splits: number of folds

        shuffle: whether to shuffle the data before splitting into batches

        random_state: when shuffle is True, random-state affects the ordering of the indices, which
        controls the randomness of each fold.
        """
        return KFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)

    def leave_one_group_out_cv_generator(self) -> LeaveOneGroupOut:
        """Set up a leave one group out cross-validation strategy."""
        return LeaveOneGroupOut()

    def shuffle_split_cv_generator(self, n_splits: int, test_size: float = 0.2) -> ShuffleSplit:
        """Set up a shuffle split cross-validation strategy."""
        return ShuffleSplit(n_splits=n_splits, test_size=test_size, random_state=0)

    def stratified_kfold_cv_generator(self,
                                      n_splits: int,
                                      shuffle: bool= False,
                                      random_state: int | None = None) -> StratifiedKFold:
        """
        Set up a stratified k-fold cross-validation strategy.

        Parameters
        ----------
        n_splits: number of folds

        shuffle: whether to shuffle the data before splitting into batches

        random_state: when shuffle is True, random-state affects the ordering of the indices, which
        controls the randomness of each fold.
        """
        return StratifiedKFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)

    def time_series_split_cv_generator(self, n_splits: int) -> TimeSeriesSplit:
        """
        Set up a time series split cross-validation strategy.

        Parmeters
        ---------
        n_splits: number of splits
        """
        return TimeSeriesSplit(n_splits=n_splits)


    ################################
    # MANUAL HYPERPARAMETER TUNING #
    ################################
    def _hyperparameter_loop_recurcive(self,
                                       data: pd.DataFrame,
                                       targets: pd.Series,
                                       scores: dict[str, list[float|int]],
                                       index: int,
                                       **hyperparameters):
        """
        Use recursion to build a nested for loop for each hyperparameters in order to perform
        cross-validation and tuned them.
        """
        if index < len(hyperparameters):
            name = list(hyperparameters.keys())[index]
            for value in hyperparameters[name]:
                # Set hyperparameter value
                self.set_hyperparameters(**{name: value})

                # Recursive call
                self._hyperparameter_loop_recurcive(data,
                                                    targets,
                                                    scores,
                                                    index+1,
                                                    **hyperparameters)
        else:
            # Compute cross-validation
            results = self.make_cross_validate(data,
                                               targets,
                                               cv_params=CvParameters(5),
                                               return_train_score=True)

            # Save hyperparameter
            for k, v in {
                k: v for k, v in self.get_hyperparameters().items() if k in hyperparameters.keys()
            }.items() :
                scores[k].append(v)

            # Save cross-validation result
            scores["testing_mean"].append(results["test_score"].mean())
            scores["testing_std"].append(results["test_score"].std())
            if (res := {k: v for k, v in results.items() if k == "train_score"}):
                scores["training_mean"].append(res["train_score"].mean())
                scores["training_std"].append(res["train_score"].std())

    def manual_hyperparameter_tuning(self,
                                     data: pd.DataFrame,
                                     targets: pd.Series,
                                     **hyperparameters) -> dict[str, list[float|int]]:
        """Manually tuned hyperparameters."""
        # Build scores dict to keep track the mean/std testing and training error
        scores: dict[str, list[float|int]] = {k: [] for k in hyperparameters.keys()}
        scores.update(testing_mean=[], testing_std=[], training_mean=[], training_std=[])

        # Hyperparameter tuning
        self._hyperparameter_loop_recurcive(data,
                                            targets,
                                            scores,
                                            0,
                                            **hyperparameters)
        return scores


    ###################################
    # AUTOMATED HYPERPARAMETER TUNING #
    ###################################
    def _grid_search_cv(self,
                        param_grid: SearchCvHyperparamType,
                        cv: int,
                        scoring: ScoringFunctionType | None = None) -> GridSearchCV:
        """
        Hyperparameter tuning by grid-search on the training set.

        Some limitation:
        - does not scale well with the number of hyperparameters to tune
        - the grid imposes a regularity during the search which might miss better parameter
        values between two consecutive values on the grid.
        - hyperparameters value must be specified explicitly
        """
        return GridSearchCV(self.model,
                            param_grid=param_grid,
                            cv=cv,
                            n_jobs=2,
                            return_train_score=True,
                            scoring=scoring)

    def _randomized_search_cv(self,
                              param_distribution: SearchCvHyperparamType,
                             n_iter: int,
                             cv: int,
                             scoring: ScoringFunctionType | None = None) -> RandomizedSearchCV:
        """
        Hyperparameter tuning by randomized-search on the training set.

        Randomly generate the parameters candidate
        """
        return RandomizedSearchCV(self.model,
                                  param_distributions=param_distribution,
                                  n_iter=n_iter,
                                  cv=cv,
                                  verbose=1,
                                  return_train_score=True,
                                  scoring=scoring)

    def _save_results_as_dataframe(self, results: dict[str, list[float]], path: Path) -> None:
        """Print scores as a DataFrame."""
        # Build the DataFrame
        columns = [
            "param_", "mean_test_score", "std_test_score", "rank_test_score",
            "mean_train_score", "std_train_score"
        ]
        scores = {
            k.rsplit("__")[-1]: v
            for k, v in results.items()
            if [col for col in columns if col in k] # Any hyperparameter starts with param_
        }
        cv_results = pd.DataFrame(scores).sort_values("mean_test_score", ascending=False)

        # Save the DataFrame as a csv
        cv_results.to_csv(path, index=False)

    def automated_search_cv(self,
                            search_class: type[SearchCvType],
                            search_params: SearchCvParameters,
                            parameters: SearchCvHyperparamType,
                            x_train: pd.DataFrame,
                            y_train: pd.Series,
                            scoring: ScoringFunctionType | None = None,
                            path: Path | None = None,
                            search_outer_cv: SearchOuterCv | None = None) -> SearchCvType:
        """
        Perform an automated search to tune hyperparameter.

        Parameters
        ----------
        search_class: which method to apply for hyperparameter tuning. For now, either a
        grid-search or a randomized-search

        search_params: additional parameter required to perform the search method

        parameters: hyperparameter values to try out for model tuning. Either fix values for the
        grid-search or a range of values for the randomized-search.

        x_train: training data set use to train the tuned model, i.e. the model using the tuned
        hyperparameters in order to retrieve the best set of hyperparameters.

        y_train: training targets use to train the tuned model

        scoring: strategy to evaluate the performance of the search cv. The same scoring method
        will be used by the outer cv if not None.

        path: automated tuning especially for a randomized-search with a large number of iterations
        is costly. Therefore, at the end result are saved as a csv file.

        search_outer_cv: the parameter of the outer cross-validation in order to evaluate the
        generalization performance of the tuned model. If None no outer cross-validation is done.
        """
        # 1. Build an automated-search cross-validation
        match search_class:
            case cls if cls is GridSearchCV:
                search_model = self._grid_search_cv(parameters,
                                                    cv=search_params.cv,
                                                    scoring=scoring)
            case cls if cls is RandomizedSearchCV:
                self._assert_cv_parameters(["n_iter"], search_params, RandomizedSearchCV.__name__)
                search_model = self._randomized_search_cv(parameters,
                                                          cv=search_params.cv,
                                                          n_iter=getattr(search_params,
                                                                         "n_iter",
                                                                         10),
                                                          scoring=scoring)
            case _:
                raise Exception(f"Unsupported search methods to tune hyperparameters.")

        # 2. Train the model with the best set of hyperparameters
        search_model.fit(x_train, y_train)

        # 3. Display the optimum hyperparameters
        print(f"The optimum set of hyperparameters is {search_model.best_params_} with a mean "
              f"error of {search_model.best_score_:.3f} (only to select the best tuned model, "
              "to assess generalization performance perform an outer cross-validation).")

        # 4. Save the tuning result into a dataframe
        if path:
            # Revert the negation apply by the error metric to get the actual error
            if scoring and isinstance(scoring, str) and scoring.startswith("neg_"):
                search_model.cv_results_["mean_test_score"] *= -1
                search_model.cv_results_["mean_train_score"] *= -1
            self._save_results_as_dataframe(search_model.cv_results_, path)

        # 5. Compute the generalization performance of the model with the score method provide a
        #    single estimation of the generalization performance. Therefore, it's always preferable
        #    to perform a cross-validation. This pattern is called a nested cross-validation.
        if search_outer_cv is not None:
            print("\nPerform an outer cross-validation on the whole dataset to compute the "
                  "generalization performance of the model with tuned hyperparameters.")
            scores = self.make_cross_validate(search_outer_cv.x_data,
                                              search_outer_cv.y_data,
                                              search_outer_cv.cv_strategy,
                                              search_outer_cv.cv_params,
                                              scoring=scoring,
                                              return_train_score=True,
                                              model=search_model)
            self.print_cross_validate(scores)

        return search_model

    def predict_tuned_model(self,
                            search_model: SearchCvType,
                            x_test: pd.DataFrame,
                            y_test: pd.Series,
                            scoring: ScoringFunctionType | None = None) -> None:
        """Estimate the generalization performance of the tuned model."""
        # Get the testing error
        error: float = search_model.score(x_test, y_test)

        # Revert the negation apply by the error metric
        if scoring is not None and isinstance(scoring, str) and scoring.startswith("neg_"):
            error = -error

        # Print the error
        print(f"The testing error of the tuned model is {error:.3f}")


    ####################
    # VALIDATION CURVE #
    ####################
    def compute_validation_curve(self,
                                 x_data: pd.DataFrame,
                                 y_data: pd.Series,
                                 param_name: str,
                                 param_range: list[int] | npt.NDArray[np.float64|np.int64],
                                 scoring: ScoringFunctionType,
                                 score_name: str,
                                 negate_score: bool = False,
                                 cv: Tcv | None = None) -> ValidationCurveDisplay:
        """
        Use validation curve to try out various values of the given hyperparameter.

        Important parameters to tune for various type of model (there is other parameter as well):
        - for tree-based model, the max_depth hyperparameter is used to control the tradeoff
        between under-fitting and over-fitting.

        - for ensemble model, the n_estimators hyperparameter is used to control the number of
        individual estimator. For gradient-boosting it's represent the number of boosting stage and
        for random-forest the number of tree in the forest.

        - for SVM model, the svc__gamma hyperparameter is used to control the tradeoff between
        under-fitting and over-fitting
        """
        return ValidationCurveDisplay.from_estimator(self.model,
                                                     x_data,
                                                     y_data,
                                                     cv=cv,
                                                     scoring=scoring,
                                                     score_name=score_name,
                                                     param_name=param_name,
                                                     param_range=param_range,
                                                     negate_score=negate_score,
                                                     std_display_style="fill_between",
                                                     n_jobs=2)


    ##################
    # LEARNING CURVE #
    ##################
    def compute_learning_curve(self,
                               x_data: pd.DataFrame,
                               y_data: pd.Series,
                               train_sizes: npt.NDArray[np.float64],
                               cv: Tcv,
                               scoring: ScoringFunctionType,
                               score_name: str,
                               negate_score: bool = False) -> LearningCurveDisplay:
        """Use learning curve to try out various training set size."""
        return LearningCurveDisplay.from_estimator(self.model,
                                                   x_data,
                                                   y_data,
                                                   train_sizes=train_sizes,
                                                   cv=cv,
                                                   score_type="both", # both train and test errors
                                                   scoring=scoring,
                                                   score_name=score_name,
                                                   negate_score=negate_score,
                                                   std_display_style="fill_between",
                                                   n_jobs=2)


    ###############
    # TIME SERIES #
    ###############
    def time_series_detection(self,
                              x_data: pd.DataFrame,
                              y_data: pd.Series,
                              scoring: ScoringFunctionType | None = None) -> None:
        """
        Using default cross-validation strategy (with or without shuffling) for time series does
        not allow to crorectly assess the generalization performance of the model. With time series
        each sample can be influenced by prebious ones in an inherently ordered sequence.

        Parameters
        ----------
        x_data: the whole data

        x_test: the whole targets
        """
        # Set up  split parameters
        split_params = [{"shuffle": True, "random_state": 0, "sorted": True},
                        {"shuffle": False, "random_state": None, "sorted": False}]

        # Train and predict model with shuffled and sorted data. The other with unshuffled data.
        y_trains, y_tests, y_predicted = [], [], []
        for i in range(len(split_params)):
            # Split data
            split_data = sklearn_train_test_split(x_data,
                                                  y_data,
                                                  shuffle=split_params[i]["shuffle"],
                                                  random_state=split_params[i]["random_state"]
            )
            y_trains.append(split_data["y_train"])
            y_tests.append(split_data["y_test"])

            # Sort data
            if split_params[i]["sorted"]:
                for k in split_data.keys():
                    split_data[k].sort_index(ascending=True, inplace=True)

            # Train the model + prediction
            self.start(x_train=split_data["x_train"], y_train=split_data["y_train"])
            tmp = getattr(self.model, "predict")(split_data["x_test"])
            y_predicted.append(pd.Series(tmp, index=split_data["y_test"].index))

            # Compute a score
            if scoring is not None:
                self.print_r2_score(split_data["y_test"], y_predicted[i])

        # Plot
        plot_time_series_detection(y_trains, y_tests, y_predicted)
